Update ngboost
thegraphnetwork/epigraphhub_py pull request #163
Opened 2022-05-13 05:27 UTC by eduardocorrearaujo

In this PR I update some functions related to the ngboost models and add new functions related to the sklearn models and lstm models.

2022-05-13 06:21 UTC, fccoelho commented
To get started we need some refactoring in the package and module names, for example, the `get_data` module, in this PR refers to pulling data from EpigraphHub, so it should be renamed to `epigraphhub.py`. Since the library can pull data from many sources, we need to keep the names informative. Also, we should avoid hardcoding table  and schema names in the code, such as `colombia`, `casos_posotivos_covid`, we need to write functions  that are completely agnostic to the external environment, and will continue to work if schema and table names change, as long as they get all the required information when they are called.

2022-05-13 12:43 UTC, fccoelho requested changes
do a complete refactoring of the code to generalize the functions and remove hardcoded swiss data and names.

2022-05-13 12:43 UTC, fccoelho commented on epigraphhub/models/lstm_models.py
> +    Function to return a dataframe with some error metrics computed.
Be specific about what metrics are calculated.

2022-05-13 12:43 UTC, fccoelho commented on epigraphhub/models/lstm_models.py
> +    if target_curve_name != "hosp":
Still too specific for FOPH dataset.

2022-05-13 12:43 UTC, fccoelho commented on epigraphhub/models/lstm_models.py
> +    cantons,
another specifc parameter name: `cantons`

2022-05-13 12:43 UTC, fccoelho commented on epigraphhub/models/lstm_models.py
> +    :params canton: canton of interest
again

2022-05-13 12:43 UTC, fccoelho commented on epigraphhub/models/lstm_models.py
> +    all_cantons = [
Hardcoding data values. Make this a parameter

2022-05-13 12:43 UTC, fccoelho commented on epigraphhub/models/lstm_models.py
> +    cantons,
again `cantons`

2022-05-13 12:43 UTC, fccoelho commented on epigraphhub/models/lstm_models.py
> +        "LU",
Again hardcoding.

2022-05-19 11:58 UTC, eduardocorrearaujo commented on epigraphhub/analysis/clustering.py
> +    :param drop_georegions: list. Param with the georegions that will be ignored in the
I agree.

2022-08-25 11:10 UTC, closed without merging

2022-08-25 13:24 UTC, eduardocorrearaujo commented
The work has migrated to PR 165