chore(docs): Improve docstrings
thegraphnetwork/epigraphhub_py pull request #200
Opened 2022-11-29 03:04 UTC by Anavelyz

## Description

## Related Issue

## Checklist

- [ x] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/thegraphnetwork/epigraphhub_py/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I've read the [`CONTRIBUTING.md`](https://github.com/thegraphnetwork/epigraphhub_py/blob/master/CONTRIBUTING.md) guide.
- [ ] I've used pre-commit hook locally.
- [ ] I've written tests for all new methods and classes that I created.
- [ ] I've written the docstring in Google format for all the methods and classes that I used.
- [x ] Semantic-release prefix title used (case sensitive):
  - Use the prefix `chore(docs):` for Examples / docs / tutorials / dependencies update
  - Use the prefix `fix:` for a bug fix
    (non-breaking change which fixes an issue).
  - Use the prefix `chore(improvement):` for an improvement
    (non-breaking change which improves an existing feature).
  - Use the prefix `feat:` for a new feature
    (non-breaking change which adds functionality).
  - Use the prefix `BREAKING CHANGE:` for a breaking change
    (fix or feature that would cause existing functionality to change).
  - Use the prefix `chore(security):` for a security fix.

2022-11-29 03:05 UTC, xmnlab commented on epigraphhub/analysis/epistats.py
> +        exposed_cases: int
do we need this indentation?

2022-11-29 03:06 UTC, xmnlab commented on epigraphhub/data/sinan_fetch.py
> +        disease: str
I think we have extra indentation here

2022-11-29 03:07 UTC, xmnlab reviewed
I haven't read it in details, but in general it looks good to me.
@eduardocorrearaujo could you review this one by chance? thanks

2023-03-15 11:50 UTC, xmnlab commented
I think we probably should try to move this forward.

2023-03-17 23:17 UTC, Anavelyz commented
What should I do to help with this?

2023-03-25 00:32 UTC, xmnlab commented
@Anavelyz have you closed this on purpose?

2023-03-25 16:25 UTC, Anavelyz commented
> @Anavelyz have you closed this on purpose?

No, I was trying to do a fetch and deleted the commits, then git didn't see any changes so it closed

2023-03-26 16:37 UTC, xmnlab requested changes
Thanks @Anavelyz for working on that. In general looks good. Just noted that some docstrings are not in the numpydocs standard. Could you move that docstrings to numpydics too please? Thanks!!

2023-04-29 20:37 UTC, Anavelyz commented
> Thanks @Anavelyz for working on that. In general looks good. Just noted that some docstrings are not in the numpydocs standard. Could you move that docstrings to numpydics too please? Thanks!!

Ready!

2023-05-04 00:05 UTC, xmnlab commented on epigraphhub/data/foph/viz.py
> +    :Returns :
the returns sections looks wrong

2023-05-04 00:06 UTC, xmnlab requested changes
just one small comment inline. 
please fix that and ping me again and we can merge this pr. 
thanks!

2023-05-05 00:44 UTC, xmnlab approved these changes
LGTM! thanks for working on that

2023-05-05 00:44 UTC, merged