added sphinx documentation
thegraphnetwork/epigraphhub_py pull request #64
Opened 2022-01-28 16:46 UTC by fccoelho

basic setup. according to issue #56

## Type of Change

- [x ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

2022-01-30 17:02 UTC, xmnlab commented
@fccoelho where would this be published? readthedocs? github pages?

2022-01-30 17:29 UTC, fccoelho commented
This will be improved continuously, but all the initial bits and pieces are already in place.

2022-01-30 17:30 UTC, fccoelho commented
> @fccoelho where would this be published? readthedocs? github pages?

I have been using readthedocs

2022-01-31 01:22 UTC, xmnlab reviewed
In general, LGTM! just added some comments about text (btw I am not an expert in the English language).

2022-01-31 01:22 UTC, xmnlab commented on docs/source/overview.md
> +The epigraphhub library is designed to provide for external users all the analytical functionality used in powering the EpigraphHub platform and applications. In fact all application designed to run
```suggestion
The epigraphhub library is designed to provide external users with all of the analytical functionality used to power the EpigraphHub platform and applications. In fact, all applications designed to run on the EpigraphHub platform rely heavily on it.
```

2022-01-31 01:22 UTC, xmnlab commented on docs/source/overview.md
> +This library should be used by users that want to contribute to the platform as well as by users that want the borrow some of the tools developed by our team in other opensource projects.
```suggestion
This library should be used by users that want to contribute to the platform, as well as users who want the borrow some of the tools developed by our team in other open source projects.
```

2022-01-31 11:05 UTC, eduardocorrearaujo requested changes

2022-01-31 11:05 UTC, eduardocorrearaujo commented on docs/source/overview.md
> +This library should be used by users that want to contribute to the platform as well as by users that want the borrow some of the tools developed by our team in other opensource projects.
```suggestion
This library should be used by users who want to contribute to the platform and users who want to borrow some of the tools developed by our team in other open-source projects.
```

2022-02-01 07:37 UTC, merged